	## zshell stuff
export ZSH=/home/lambda/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

	## user settings
export UPDATE_ZSH_DAYS=13
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export EDITOR='nano'
# compilation flag
export ARCHFLAGS="-arch x86_64"
export SSH_KEY_PATH="~/.ssh/rsa_id"
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='nano'
else
	export EDITOR='vim'
fi

	## tty or naw
if [[ $(grep -ci "tty" <<< $(tty)) == 1 ]]; then
	ZSH_THEME="refined"
	plugins=
	(
		# git?
	)
else
	## powerlevel stuff
	POWERLEVEL9K_MODE='awesome-fontconfig'
		# lefty
	POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0b4'
	POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\ue0b5'
	# may change this later
	POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=''
	POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs newline custom_user host dir_writable)
	POWERLEVEL9K_DIR_PATH_SEPARATOR="$(printf $'\ue0b5')"
	POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
	POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
	POWERLEVEL9K_SHORTEN_DELIMITER=""
	POWERLEVEL9K_SHOW_CHANGESET=true


		# icon
	POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=""
	POWERLEVEL9K_LINUX_ICON='\uf30a'
	POWERLEVEL9K_OK_ICON='\uf00c'
	POWERLEVEL9K_ERROR_ICON='\uf467'
	POWERLEVEL9K_LOCK_ICON='\uf83d'
	POWERLEVEL9K_HOME_ICON='\ue617'
	POWERLEVEL9K_PYTHON_ICON='\uf820'
	POWERLEVEL9K_NODE_ICON='\ufbdf'
	POWERLEVEL9K_RUST_ICON='\ue7a8'
	POWERLEVEL9K_ANDROID_ICON='\ufc8e'
	POWERLEVEL9K_HOME_SUB_ICON='\uf07c'
	POWERLEVEL9K_VCS_COMMIT_ICON='\ue729'
	POWERLEVEL9K_VCS_GIT_ICON='\uf1d3'
	POWERLEVEL9K_VCS_UNTRACKED_ICON='\uf128'
	POWERLEVEL9K_VCS_UNSTAGED_ICON='\uf12a'
	POWERLEVEL9K_VCS_STAGED_ICON='\uf067'
	POWERLEVEL9K_VCS_BRANCH_ICON='\ue0a0'
	POWERLEVEL9K_INCOMING_CHANGES_ICON='\uf063'
	POWERLEVEL9K_OUTGOING_CHANGES_ICON='\uf062'
	POWERLEVEL9K_VCS_BOOKMARK_ICON='\uf02e'
	POWERLEVEL9K_SSH_ICON='\uf120'
	POWERLEVEL9K_HOME_SUB_ICON='\ue5ff'
	POWERLEVEL9K_FOLDER_ICON='\ue5fc'
	# it me!
	POWERLEVEL9K_CUSTOM_USER="echo '𝝺'"
		# colors

	POWERLEVEL9K_CUSTOM_USER_BACKGROUND='016'
	POWERLEVEL9K_CUSTOM_USER_FOREGROUND='011'
	POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='011'
	POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='232'
	POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='097'
	POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='231'
	POWERLEVEL9K_DIR_HOME_BACKGROUND='097'
	POWERLEVEL9K_DIR_HOME_FOREGROUND='231'
	POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='097'
	POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='231'
	POWERLEVEL9K_HOST_LOCAL_BACKGROUND='097'
	POWERLEVEL9K_HOST_LOCAL_FOREGROUND='231'
	POWERLEVEL9K_HOST_SSH_BACKGROUND='097'
	POWERLEVEL9K_HOST_SSH_FOREGROUND='016'
	POWERLEVEL9K_STATUS_OK_BACKGROUND='072'
	POWERLEVEL9K_STATUS_OK_FOREGROUND='231'
	POWERLEVEL9K_STATUS_ERROR_BACKGROUND='124'
	POWERLEVEL9K_STATUS_ERROR_FOREGROUND='231'
	POWERLEVEL9K_TIME_BACKGROUND='016'
	POWERLEVEL9K_TIME_FOREGROUND='011'
	POWERLEVEL9K_OS_ICON_BACKGROUND='016'
	POWERLEVEL9K_OS_ICON_FOREGROUND='011'
	POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='016'
	POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='072'

	POWERLEVEL9K_VCS_CLEAN_BACKGROUND='016'
	POWERLEVEL9K_VCS_CLEAN_FOREGROUND='048'
	POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='016'
	POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='160'
	POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='016'
	POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='231'

	#POWERLEVEL9K_NODE_VERSION_BACKGROUND='072'
	#POWERLEVEL9K_NODE_VERSION_FOREGROUND='231'

		# righty
	POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\ue0b6'
	POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\ue0b7'
	POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time)
	#POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
	ZSH_THEME="powerlevel9k/powerlevel9k"

	## plugins take 2
	plugins=(
		git
		zsh-autosuggestions
		Z
	)
fi

# load plugins
source $ZSH/oh-my-zsh.sh

# I don't give a fuck
eval $(thefuck --alias)
